#!/bin/bash
quilt install @./binder/quilt.yml

# extensions for ipywidgets and python-markdown (see https://github.com/binder-examples/jupyter-extension)
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust ./jupyter/basics/python-markdown/markdown-python.ipynb
jupyter trust ./jupyter/basics/python-markdown/markdown-quilt.ipynb
jupyter trust ./jupyter/case-notebook/case-notebook-first.ipynb

# Installing and Activating the Case Notebook
cp -r ./nbextensions/case-notebook /srv/conda/share/jupyter/nbextensions/
jupyter nbextension install /srv/conda/share/jupyter/nbextensions/case-notebook/
jupyter nbextension enable case-notebook/main
